server:
  port: 1127
appconfig:
  serverName: jylFrame
  host: http://localhost:1127/hello
  isTestServer: true
  jdbcDriver: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:3306/luframe
  jdbcUsername: root
  jdbcPassword: 111111
spring:
  thymeleaf:
    cache: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order:


